# Generated by Django 5.1.4 on 2026-05-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id_feriado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Internacional', 'Internacional'), ('Nacional', 'Nacional'), ('Departamental', 'Departamental'), ('Municipal', 'Municipal'), ('Institucional', 'Institucional')], max_length=20)),
            ],
            options={
                'db_table': 'feriado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unidad_organizacional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntentosAcceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=100)),
                ('roles', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intentos_acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
